# Generated by Django 4.2.3 on 2024-03-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Book Name')),
                ('author', models.CharField(max_length=255, verbose_name='Book Author')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('edition_number', models.IntegerField(verbose_name='Edition Number')),
                ('publish_date', models.DateField(verbose_name='Date of Publish')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(max_length=20, unique=True, verbose_name='Book Number')),
                ('in_stock', models.PositiveIntegerField(default=0, verbose_name='In Stock')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book', verbose_name='Book')),
            ],
        ),
    ]
